"""Guards for the「五个因子都选上是不是更好」claim, and for the trap entry that answers it.

Two regressions are pinned here.  Both were found on 2026-09-29 while answering that
question, and neither was visible from a green suite.

1. **The console could not express the configuration.**  `PRESETS` carried a four-factor
   and a three-factor entry but no "all five", so "tick all five factors" was only
   askable by hand-editing an override.  A question with no button is a question that
   does not get answered.

   **Update (2026-09-29, after promotion).**  The all-five set is now the accepted basis,
   so the original regression is unreachable -- but the *mirror image* of it is not: if
   the narrower control arm loses its button, the comparison becomes unaskable while
   every number on the page still renders.  The guard below pins that instead.

2. **The `rev_short` trap entry quoted evidence from a different construction.**  It
   cited the *standalone reversal book* (gross Sharpe negative at every horizon) and the
   *book-level blend* (optimal overlay weight 0.0), while the user was changing the
   *composite score*.  Measured on the composite, adding `rev_short` at the 1-day grid
   **raises** the full-sample Sharpe (1.862 -> 1.937 in `34_neutralisation_study.csv`),
   so the stated reason was contradicted by the project's own artifact.  The entry also
   quoted five gross Sharpes that appear in **no artifact on disk**, with no
   `RECORDED_NOTE`, while the neutralisation entry directly above it carries one.

3. **The trap entry's reason (3) was a cross-tag comparison.**  It read "1.9377 beats the
   project's own `deflated_haircut` 1.9375 by 0.0002" -- but `16_multiplicity_summary.csv`
   is regenerated by *each* run, so 1.9375 belonged to the **previous** basis (`v4_1d`)
   while 1.9377 was this one's.  Read per tag, neither basis clears its own haircut and
   the five-factor set is in fact *closer* (`v4_1d` -0.117, `v5_1d_all5` -0.020).  The
   sentence was deleted rather than reworded; the guard below keeps it from coming back.

The claim itself is pinned too: the five-factor arm is measurably better at the 1-day
grid and measurably worse at the 3-day grid, and its gain shows up in the **profit
factor** while the **daily win rate does not separate the arms at all** (51.62% /
50.91% / 51.43% against a ≈1.09pp standard error).  An edit that flattens the story to
one direction -- in either direction -- goes red.
"""
from __future__ import annotations

import json
import os
import re

import pandas as pd
import pytest

from webapp import spec

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
TAG = spec.OPTIMAL_TAG
# The basis this one replaced.  Only used to prove the console does *not* quote its
# per-tag numbers -- `16_multiplicity_summary.csv` is regenerated by every run, so mixing
# the two tags' haircuts is a comparison across two different samples.
PREV_TAG = "v4_1d"


def _trap_body(subset) -> str:
    """The `rev_short` trap body for a factor subset.  Fails loudly if the warning is gone."""
    warns = spec.check_traps({"factors.subset": list(subset)}, dict(spec.OPTIMAL_CLI))
    hit = [w for w in warns if w["key"] == "factors.rev_short"]
    assert hit, f"check_traps no longer warns for subset={list(subset)}"
    return hit[0]["body"]


def _pair_in(body: str, a: float, b: float, gap: int = 14) -> bool:
    """True if `a` and `b` appear as an *adjacent pair*, in either order.

    Lone-number checks are useless for these values: `1.957` is a substring of `1.9570`,
    and several of them recur in the body, so `"1.937" in body` passes on text that has
    lost the claim entirely.  Requiring the two numbers to sit within `gap` characters of
    each other means deleting either one -- or deleting the sentence they belong to --
    turns the test red, without pinning the connecting prose.
    """
    sa, sb = f"{a:.3f}", f"{b:.3f}"
    pat = rf"{re.escape(sa)}.{{0,{gap}}}{re.escape(sb)}|{re.escape(sb)}.{{0,{gap}}}{re.escape(sa)}"
    return re.search(pat, body) is not None


def _read_table(name: str, tag: str | None = None) -> pd.DataFrame:
    p = os.path.join(ROOT, "artifacts", tag or TAG, "tables", name)
    if not os.path.exists(p):
        pytest.skip(f"artifact missing (run the producing stage first): {p}")
    return pd.read_csv(p)


def _sharpe_by_label(tag: str) -> dict:
    t = _read_table("exp_factor_set_grid.csv", tag=tag)
    return dict(zip(t["label"], t["Sharpe"]))


# ---------------------------------------------------------------------------
# 1. the console must be able to express the configuration *and* its control arm
# ---------------------------------------------------------------------------
def test_the_control_arm_of_the_factor_comparison_still_has_a_button():
    """A preset must exist for each arm the claim compares.

    The original regression was 'tick all five factors' having no button at all.  After
    promotion the all-five set *is* the accepted preset, so that is unreachable -- but the
    mirror image is not: `PRESETS` is also the only place the narrower control arm is
    expressed, and deleting it makes the comparison unaskable while every number on the
    page still renders.  A question with no button is a question that does not get
    answered, whichever arm is missing.

    The arm tuples are the ones the trap entry and `exp_factor_set_grid.csv` actually
    quote numbers for; the accepted set is read from `OPTIMAL_OVERRIDES` so that moving
    `ACCEPTED_FACTORS` moves this test with it instead of leaving a stale list behind.
    """
    subsets = [tuple(p["overrides"].get("factors.subset", ())) for p in spec.PRESETS]
    accepted = tuple(spec.OPTIMAL_OVERRIDES["factors.subset"])
    assert accepted in subsets, (
        "no preset selects the accepted factor set -- the console cannot express the "
        "configuration the claim is about")
    for arm in (("range_pos", "hitrate"),               # v2(rp,hr)     -- the control
                ("range_pos", "hitrate", "rev_short")):  # only-rev_short-added control
        assert arm in subsets, (
            f"no preset selects {arm} -- the comparison arm has no button, so the claim "
            f"can no longer be asked in the console")
    assert accepted != ("range_pos", "hitrate"), (
        "the accepted arm and the control arm are the same configuration, so the "
        "comparison is vacuous")
    # The presets must still be *distinct configurations*, not two labels on one button:
    # a duplicated preset is how a comparison silently stops being a comparison.  `cli`
    # is part of the key because two presets that differ only in the bar/frequency really
    # are different runs.
    seen: dict[str, str] = {}
    for p in spec.PRESETS:
        key = json.dumps({"cli": p.get("cli"), "overrides": p["overrides"]},
                         sort_keys=True, default=str)
        assert key not in seen, (
            f"presets {seen.get(key)!r} and {p['id']!r} are the same configuration -- "
            f"two buttons that look different but are not")
        seen[key] = p["id"]


# ---------------------------------------------------------------------------
# 2. the trap entry must be about the thing the user changed
# ---------------------------------------------------------------------------
def test_rev_short_trap_cites_both_constructions():
    """Both constructions, not only the standalone book."""
    body = _trap_body(spec.FACTOR_NAMES)
    assert "30_reversal_book.csv" in body, "standalone-book evidence must be cited"
    assert "34_neutralisation_study.csv" in body, (
        "the composite counter-evidence must be cited: without it the entry reads as "
        "'rev_short is bad, never put it in the subset', which the project's own "
        "artifact contradicts")
    assert "独立 book" in body and "复合分数" in body


def test_rev_short_trap_does_not_quote_orphan_numbers():
    """The gross-Sharpe list that matched no artifact must not come back."""
    body = _trap_body(spec.FACTOR_NAMES)
    for orphan in ("0.569", "0.976", "0.966", "0.832", "0.859"):
        assert orphan not in body, (
            f"{orphan} came from a gross-Sharpe list that matches no artifact on disk. "
            f"Cite the artifact and the column name instead of embedding the numbers.")


def test_rev_short_trap_composite_numbers_match_the_artifact():
    """The load-bearing pair must be readable out of the artifact, not remembered."""
    t = _read_table("34_neutralisation_study.csv")
    four = float(t.loc[t.label == "spec4(mom,flow,rp,hr)|neutralize=False",
                       "Sharpe"].iloc[0])
    five = float(t.loc[t.label == "all5+rev_short|neutralize=False", "Sharpe"].iloc[0])
    assert five > four, (
        "the artifact no longer supports 'adding rev_short as a composite component "
        "raises Sharpe' -- the trap wording has to change with it")
    body = _trap_body(spec.FACTOR_NAMES)
    # The *pair*, not the individual numbers: "1.937" on its own is also a substring of
    # "1.9375" and of the haircut sentence, so a loose check passes on a mutated text.
    assert _pair_in(body, four, five), (
        f"trap text must quote the artifact's {four:.3f} / {five:.3f} as a pair "
        f"(from 34_neutralisation_study.csv)")


def test_rev_short_trap_does_not_revive_the_cross_tag_haircut_claim():
    """Reason (3) used to compare this tag's Sharpe against the *previous* tag's haircut.

    `16_multiplicity_summary.csv` is regenerated by every run, so `v4_1d`'s
    `deflated_haircut` and `v5_1d_all5`'s Sharpe come from different samples.  The old
    sentence ("1.9377 beats the project's own haircut 1.9375 by 0.0002") read as a pass
    while being directionally wrong: per tag, neither basis clears its own haircut, and
    the five-factor set is the *closer* of the two.  It was deleted rather than reworded,
    and this pins that it does not come back in the old form.
    """
    stale = float(_read_table("16_multiplicity_summary.csv",
                              tag=PREV_TAG)["deflated_haircut"].iloc[0])
    body = _trap_body(spec.FACTOR_NAMES)
    assert f"{stale:.4f}" not in body, (
        f"{stale:.4f} is {PREV_TAG}'s deflated_haircut, not {TAG}'s -- quoting it beside "
        f"this tag's Sharpe is exactly the cross-tag comparison the promotion corrected. "
        f"If a haircut is cited, cite the one from artifacts/{TAG}/tables/.")


def test_rev_short_trap_quotes_the_fold_means_from_the_artifact():
    """Reason (2) is a walk-forward mean: recompute it, so a rebuild turns this red
    instead of leaving a stale number in the console."""
    f = _read_table("34b_neutralisation_folds.csv")
    two_cfg, five_cfg = "v2(rp,hr)|neutralize=False", "all5+rev_short|neutralize=False"
    for cfg in (two_cfg, five_cfg):
        assert len(f[f.config == cfg]) > 0, f"{cfg} missing from the fold table"
    two = f[f.config == two_cfg]
    five = f[f.config == five_cfg]
    assert five["test_sharpe"].mean() < two["test_sharpe"].mean(), (
        "the artifact no longer supports 'the five-factor OOS mean is not better'")
    assert five["train_sharpe"].mean() > two["train_sharpe"].mean(), (
        "the artifact no longer supports 'the five-factor TRAIN mean is higher'")
    body = _trap_body(spec.FACTOR_NAMES)
    # Pairs, not lone numbers -- see the note in the composite test above.
    for a, b in ((five["test_sharpe"].mean(), two["test_sharpe"].mean()),
                 (five["train_sharpe"].mean(), two["train_sharpe"].mean())):
        assert _pair_in(body, a, b), (
            f"trap must quote the recomputed fold means {a:.3f} / {b:.3f} as a pair")


# ---------------------------------------------------------------------------
# 3. the finding itself: better at 1 day, worse at 3 days, and not a win-rate gain
# ---------------------------------------------------------------------------
def test_the_five_factor_gain_does_not_survive_the_other_grid():
    """The improvement is a property of the (factor set, grid) pair, not of the set."""
    g = _sharpe_by_label("factor_set_grid")
    assert g["all5(+rev_short)@1d"] > g["v2(rp,hr)@1d"], "no longer wins at 1 day"
    assert g["all5(+rev_short)@3d"] < g["v2(rp,hr)@3d"], (
        "the ordering no longer reverses at 3 days -- if the reversal really went away, "
        "the robustness verdict in FINDINGS Q32 has to be revisited")


def test_the_five_factor_gain_is_not_a_win_rate_gain():
    """闸门 22: the improvement is payoff asymmetry, not hit rate.

    The user's claim was specifically「胜率更好」.  It is **not decidable**: at the 1-day
    grid the three win rates are 51.62% / 50.91% / 51.43%, and with n ≈ 2097 days the
    standard error is ≈1.09pp, so the largest gap is 0.34σ.  This test pins the two
    halves of that statement -- the win rate does not separate the arms, and the profit
    factor does -- so a wording change in either direction has to come with evidence.
    """
    t = _read_table("exp_factor_set_grid.csv", tag="factor_set_grid")
    w = dict(zip(t["label"], t["win_rate_daily"]))
    pf = dict(zip(t["label"], t["profit_factor_daily"]))
    d_win = w["all5(+rev_short)@1d"] - w["v2(rp,hr)@1d"]
    assert abs(d_win) < 0.005, (
        f"the daily win rates now differ by {d_win:+.4f}, which is no longer inside the "
        f"≈1.1pp standard error -- 「胜率更好」would have become a real claim and the "
        f"preset/trap wording must be rewritten")
    assert pf["all5(+rev_short)@1d"] > pf["v2(rp,hr)@1d"], (
        "the gain has to show up in the profit factor if it is not in the win rate")


def test_the_five_factor_gain_is_not_the_equal_weight_degeneracy():
    """`construct.inverse_vol_weights` equal-weights the book whenever `cap*n <= 1`, and
    this project already measured that in a narrow cross-section equal weight *is* the
    risk control.  So 'the five-factor arm simply selects fewer names per side' is the
    first alternative explanation, and it has to stay excluded."""
    t = _read_table("exp_factor_set_grid.csv", tag="factor_set_grid")
    nl = dict(zip(t["label"], t["sel_n_long_med"]))
    eq = dict(zip(t["label"], t["frac_eqw_either"]))
    assert nl["all5(+rev_short)@1d"] == nl["v2(rp,hr)@1d"], (
        "selection width differs between the arms, so the comparison is confounded")
    assert eq["all5(+rev_short)@1d"] <= eq["v2(rp,hr)@1d"], (
        "the five-factor arm triggers the equal-weight fallback more often than the "
        "accepted arm -- the gain could be the sizing degeneracy, not factor information")
